version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ebooks
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
